---
title: "cross validation"
author: "Chen Liang"
date: "2023-11-14"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(modelr)
library(mgcv)
set.seed(1)
```

# Nonlinear data and cv
```{r}
nonlin_df = 
  tibble(
    id = 1:100,
    x = runif(100, 0, 1),
    y = 1 - 10 * (x - .3) ^ 2 + rnorm(100, 0, .3)
  )

nonlin_df |> 
  ggplot(aes(x = x, y = y)) + 
  geom_point()
```

## do the train /test split

```{r }
train_df = sample_n(nonlin_df, 80)
test_df = anti_join(nonlin_df, train_df, by = "id")

ggplot(train_df, aes(x = x, y = y)) + 
  geom_point() + 
  geom_point(data = test_df, color = "red")
```

```{r}
linear_mod = lm(y ~ x, data = train_df)
smooth_mod = mgcv::gam(y ~ s(x), data = train_df)
wiggly_mod = mgcv::gam(y ~ s(x, k = 30), sp = 10e-6, data = train_df)
```


```{r}
train_df |>
  modelr::add_predictions(smooth_mod) |>
  ggplot(aes(x = x, y = y)) + 
  geom_point() +
  geom_line(aes(y=pred))
```

RMSE on training data can be missleading
```{r}
rmse(linear_mod, train_df)
rmse(smooth_mod, train_df)
rmse(wiggly_mod, train_df)
```

```{r}
rmse(linear_mod, test_df)
rmse(smooth_mod, test_df)
rmse(wiggly_mod, test_df)
```

## use model for CV
```{r}
cv_df = 
  crossv_mc(nonlin_df, 100) 
```

```{r}
cv_df |> pull(train) |> nth(1) |> as_tibble()

cv_df |> pull(test) |> nth(1) |> as_tibble()

cv_df =
  cv_df |> 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble))
```

```{r}
lin_mod_function = function(df){
  lm(y~x,data=df)
}

cv_results = 
  cv_df |>
  mutate(
    linear_fit=map(train,\(df)lm(y~x,data =df)),
    smooth_fit= map(train, ~mgcv::gam(y ~ s(x), data = .x)),
    wiggly_fit  = map(train, ~gam(y ~ s(x, k = 30), sp = 10e-6, data = .x))
  ) |>
  mutate(
    rmse_linear = map2_dbl(linear_fit, test, \(mod,df)rmse(mod,df)),
    rmse_smooth = map2_dbl(smooth_fit, test, ~rmse(model = .x, data = .y)),
    rmse_wiggly = map2_dbl(wiggly_fit, test, ~rmse(model = .x, data = .y)))
```

```{r}
cv_results |> 
  select(starts_with("rmse")) |> 
  pivot_longer(
    everything(),
    names_to = "model_type", 
    values_to = "rmse",
    names_prefix = "rmse_") |>
  mutate(model = fct_inorder(model_type)) |> 
  ggplot(aes(x = model, y = rmse)) + geom_violin()

```
