---
title: "linear_model"
author: "Chen Liang"
date: "2023-11-09"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(tidyverse)
library(p8105.datasets)

set.seed(1)
data("nyc_airbnb")
```

```{r}
nyc_airbnb = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) |> 
  filter(borough != "Staten Island") |> 
  select(price, stars, borough, neighborhood, room_type)
```

```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
```

```{r}
fit 
summary(fit)
summary(fit)$coef
coef(fit)
fitted.values(fit)
```

```{r}
fit |> 
  broom::glance()
```

tidy up the coefficients
```{r}
fit |> 
  broom::tidy() |>
  mutate(term=str_replace(term, "borough","Borough: ")) |>
  select (term, estimate, p.value) |>
  knitr::kable(digits = 3)
```

#quick look at diagnostics
```{r}
nyc_airbnb |>
  modelr::add_residuals(fit) |>
  ggplot(aes(x = price, y = resid)) + 
  geom_violin()
```


```{r}
nyc_airbnb |> 
  modelr::add_residuals(fit) |> 
  ggplot(aes(x = stars, y = resid)) + geom_point()
```

# Hypothesis testing

fit a "null" and "alternative" model
```{r}
fit_null = lm(price ~ stars + borough, data = nyc_airbnb)
fit_alt = lm(price ~ stars + borough + room_type, data = nyc_airbnb)

```


```{r}
anova(fit_null, fit_alt) |> 
  broom::tidy()

```

## Borough-level differences
```{r}
fit=
  nyc_airbnb |> 
  lm(price ~ stars * borough + room_type * borough, data = _)

fit |>
  broom::tidy()
```

```{r}
airbnb_lm= function(df){
  lm(price~stars+ room_type, data=df)
}

nest_lm_res =
nyc_airbnb |>
  nest(df = -borough) |>
  mutate(
    models = map(df,airbnb_lm),
    results = map(models, broom::tidy)) |>
  select(-df, -models) |> 
  unnest(results)

```

```{r}
nest_lm_res |> 
  select(borough, term, estimate) |> 
  mutate(term = fct_inorder(term)) |> 
  pivot_wider(
    names_from = term,
    values_from = estimate) |> 
  knitr::kable(digits = 3)
```

```{r}


```


```{r}


```


```{r}


```



```{r}


```


```{r}


```


```{r}


```


```{r}


```

```{r}


```



